name: Github Actions Sample
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/checkout@v4
    
  
  show_workflow_name:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: ${{ github.workflow }}
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - run: echo "WorkflowName => ${WORKFLOW_NAME}"\n "RunNumber => ${RUN_NUMBER}"

  log-annotation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error"
      - run: echo "::warning::This is warning"
      - run: echo "::notice::This is notice"
  job-suumary:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"
