name: Github Actions Sample
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/checkout@v4
    
  
  show_workflow_name:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: ${{ github.workflow }}
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - run: echo "WorkflowName => ${WORKFLOW_NAME}"\n "RunNumber => ${RUN_NUMBER}"

  log-annotation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error"
      - run: echo "::warning::This is warning"
      - run: echo "::notice::This is notice"
  job-suumary:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

  # josのデータ出力
  # 1. ステップにidキーを設定
  # 2. ステップ内でGITHUB_OUTPU環境変数へ値を書き出す
  # 3. 出力値をジョブのoutputsキーへstepsコンテキスト経由でセット
  share-data-between-jobs-before:
    runs-on: ubuntu-latest
    steps:
      - id: data_generate
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.data_generate.outputs.result }}
  share-data-between-jobs-after:
    runs-on: ubuntu-latest
    needs: [share-data-between-jobs-before]
    steps:
      - env:
          RESULT: ${{ needs.share-data-between-jobs-before.result }}
        run: |
          [ ! -z "${RESULT}" ] && echo "${RESULT}" || echo "RESULT は空です"
