name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World"
      - uses: actions/checkout@v4
    
  
  show_workflow_name:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: ${{ github.workflow }}
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - run: echo "WorkflowName => ${WORKFLOW_NAME}"\n "RunNumber => ${RUN_NUMBER}"
