name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "The password is ${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD$?}"
